### ISSUE TITLE
Maybe we should stop collecting inputs

### ISSUE THREAD

**Issue by Moelf** [Moelf/AoC2023#26]
https://www.reddit.com/r/adventofcode/wiki/faqs/copyright/inputs/

@RongkunWang @Cryptum169

**Comment by RongkunWang** [comment]
let's keep this repo private? Looks like there's only 3/4 of us.

**Comment by Moelf** [comment]
fixed by #27 

basically I think we should:
- keep uploading the `<day>_example.txt` and its solution, since they are fine to be shared.
- keep your local inputs and solutions
- at least `python` and `cpp` solutions will be run on my input
